### ISSUE TITLE
\ifprefchar missing in biblatex1.sty

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#365]
The following MWE throws the understandable error `undefined control sequence`, the new `\ifprefchar` has not been added to `biblatex1.sty`.

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[american]{babel}
\usepackage{csquotes}
\usepackage[backend=bibtex]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\nocite{brandt}
\printbibliography
\end{document}
```

The would probably need to be the `biblatex1.sty`-equivalent of https://github.com/plk/biblatex/commit/c2f0e7b90d5194cab7f79740638430441f6b8e9f.

**Comment by plk** [comment]
Fixed in DEV branch.

**Comment by moewew** [comment]
Thanks.

One tiny problem remains

`\mathchardef\blx@sf@apo` needs to be renamed to `\mathchardef\blx@sf@prefixchar` and `\blx@namecodes` needs to be brought in line with `biblatex2.sty`.

**Comment by plk** [comment]
Ah, of course, thanks. Done in DEV branch. Will upload new 3.3 in a moment.
