### ISSUE TITLE
\cite command within bib entry regression

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#407]
The following code works with v3.3, but not with latest v3.4. References are never resolved no matter how many times `biber` and `pdflatex` are run, despite actual PDF output being correct. (I know it is a little odd to want to do this... My actual style does something slightly different. I'm open to a discussion on how to do what I want to in a better way.)

```
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{betz:1996,
  author = {Betz, Hans Dieter},
  title = {The Greek Magical Papyri in Translation, Including the Demotic Spells},
  edition = {2},
  location = {Chicago},
  publisher = {University of Chicago Press},
  date = {1996}
}
@book{PGM:betz,
  editor = {\nocite{betz:1996}Preisendaz, Karl},
  title = {Papyri Graecae Magicae: Die griechischen Zauberpapyri},
  shorttitle = {PGM},
  edition = {2},
  location = {Stuttgart},
  publisher = {Teubner},
  date = {1973/1974},
  shorthand = {PGM},
  options = {skipbib}
}
\end{filecontents}
\usepackage[style=verbose,backend=biber]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\strut\vfill
\autocite{PGM:betz}
\printbiblist{shorthand}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
There were several fixes in 3.4 for problems with such issues in cases which are a bit more, well, legitimate ... so, I don't really think this is supported - what are you trying to do? It looks like something that the "related" feature should be handing.

**Comment by dcpurton** [comment]
I can provide a more realistic example. I know the above is not legitimate - it just happens to demonstrate the problem.

If I use the `related` field, how can I *force* the entry pointed to by `related` to be in the bibliography?

**Comment by dcpurton** [comment]
I did a bisect. The actual commit that broke things was @163849de21be859ffc3aed17c843ace7a0f18bd4

**Comment by dcpurton** [comment]
Here's a more specific example of what I want. Except that it doesn't work... I don't understand why nothing is printed in the parentheses in the footnote. Also, I don't want to use `xref` since the `mincrossrefs` option can not be set independently for `xref` (I want `mincrossrefs=1`) and `crossref` (I want `mincrossrefs=3`). In my actual style I used a new field called `sblxref` which *always* appears in the bibliography unless explicitly skipped with `option = {skipbib}`. I have done this by inserting `\nocite{sblxref}` in every citation, as I couldn't figure out another way of forcing it to appear in the bibliography.

The problems with the below example are therefore:
* footnote should be: **¹*PGM* III. 1–164 (Betz).** instead of **¹*PGM* III. 1–164 ().**
* doesn't include `betz:1996` in bibliography unless `minicrossrefs=1`

Any help in doing this better is much appreciate, as I know there are a number of hacks involved.

(BTW, this is just a simple example, sometimes book citations in full must go in the parentheses; sometimes shorthands; sometimes full book citation for first citation and shorthand for subsequent, etc.)

```
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{betz:1996,
  author = {Betz, Hans Dieter},
  title = {The Greek Magical Papyri in Translation, Including the Demotic Spells},
  edition = {2},
  location = {Chicago},
  publisher = {University of Chicago Press},
  date = {1996}
}
@book{PGM:betz,
  editor = {Preisendaz, Karl},
  title = {Papyri Graecae Magicae: Die griechischen Zauberpapyri},
  edition = {2},
  location = {Stuttgart},
  publisher = {Teubner},
  date = {1973/1974},
  shorthand = {\mkbibemph{PGM}},
  options = {skipbib,useeditor=false},
  xref = {betz:1996}
}
\end{filecontents}
\usepackage[style=verbose,mincrossrefs=1,backend=biber]{biblatex}
\addbibresource{\jobname.bib}
\renewbibmacro*{cite}{%
  \printfield{shorthand}%
  \setunit{\space}%
  \printfield{postnote}%
  \clearfield{postnote}%
  \setunit{\space}%
  \printtext[parens]{\entrydata{\thefield{xref}}{\printnames[labelname]{author}}}%
}
\DeclareFieldFormat{postnote}{#1}
\begin{document}
\strut\vfill
\autocite[III. 1--164]{PGM:betz}
\printbiblist{shorthand}
\printbibliography
\end{document}
```

**Comment by dcpurton** [comment]
Oh! It looks like \entrydata also used to work. First bad commit was: @163849de21be859ffc3aed17c843ace7a0f18bd4 Same as what I found above...

**Comment by plk** [comment]
I would post to tex.stackexchange.com to ask about how to do this - it looks like it should be done with related entries. I will look into whether there is a bug involved.

**Comment by dcpurton** [comment]
Surely there is a bug regarding `\entrydata`? My second example does not do anything odd with citations within citations. Or else, I misunderstand badly how `\entrydata` works?

I might post to tex.stackexchange.com anyway. As I would like to get rid of the \nocite hack. It adds an extra biber/latex pass which would be nice to avoid.

**Comment by dcpurton** [comment]
More info: `\entrydata` does work. It just doesn't work if with the `skipbib` option in `PGM:betz`. Initially it does, but then it asks for another LaTeX run, and from then on nothing is printed. This also happens if I combine a `related` field with the `skipbib` option.

**Comment by plk** [comment]
I think this is a reasonable argument for having a `minxrefs` option in biblatex - I assume that would fix your problem?

**Comment by dcpurton** [comment]
Yes, a `minxrefs` option would be the neatest solution and remove the need for a `\nocite{}` hack. I nearly put a feature request in for this when I first came across the problem.

I don't think this will help with the second problem of `\entrydata` interacting with `skipbib` though, which seems unrelated. (Sorry to combine two issues in one!)

**Comment by dcpurton** [comment]
Where is `mincrossrefs` and the hypothetical `minxrefs` implemented? Is it in `biber`? I couldn't figure out how this worked when I first looked at this.

**Comment by plk** [comment]
It's in biber, yes. You can now get the latest 3.4 biblatex and 2.5 biber and this should work now - `minxrefs` is now a separate option but by default set to the same as `mincrossrefs`. There was a commit recently (05fcfa5699934499148f3f910a86444ed352d2e4) which addressed `\entrydata` in related items not working (now it does) but it does depend on you using a real related entry and not `\entrydata` directly. The issue is that `skipbib` removes the data from context and so `\entrydata` won't find it. The related entry system is the way to do these things - that's what it's for.

**Comment by dcpurton** [comment]
OK! Thanks. I'll look at things.

however, I gather from what you're saying that I still won't be able to use `xref`... I'll have to replace it with a `related` field and a `relatedtype` field. The `skipbib` problem crops up surprisingly often for me.

I used to just use my own custom `sblxref` field. Then use a variety of hacks to get the right data into the right places...

I get that it's more proper... but it is a step backwards in ease of use for those who are using my style :(. And it did work just fine up until only a couple of weeks ago!

**Comment by plk** [comment]
Hmm, well, try the xref thing first and update here with results and then we can see if there is something else to fix.

**Comment by plk** [comment]
It's not clear to me what the point is is having `PGM:betz` at all since nothing from it is printed in the citation and it's completely ignore from the bibliography (`skipbib=true`). Why not just cite `betz:1996` directly?

**Comment by dcpurton** [comment]
`PGM:betz` appears in the list of shorthands, while `betz:1996` appears in the bibliography. *The Society of Biblical Literature Handbook of Style* has lots of quirks like this for its more specialised citation types.

Now for the update. The good news is that `minxrefs` works as expected. The bad news is that there is still a bug in the `related` code connected with the `skipbib` option. I've put a new MWE below. Here's what happens at each step.

$ `pdflatex` → ¹**PGM:betz**.
  - prompted to run `biber` and then rerun `latex`

$ `biber` → ¹*PGM* III. 1–164 (Betz).
  - document is **correct**; prompted to rerun `latex`

$ `pdflatex` → ¹*PGM* III. 1–164 ().
  - "Betz" has **dropped out**; prompted to rerun `latex`

$ `pdflatex` → ¹*PGM* III. 1–164 ().
  - "Betz" still **missing**; no further prompts to rerun `latex`

Note that this bug occurs even if I take out the custom macros from the below example. If I remove `skipbib` from `PGM:betz` then there is one less `pdflatex` run required and everything works as expected. So it appears that the related entry system does not cope with `skipbib` either.

```TeX
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{betz:1996,
  author = {Betz, Hans Dieter},
  title = {The Greek Magical Papyri in Translation, Including the Demotic Spells},
  edition = {2},
  location = {Chicago},
  publisher = {University of Chicago Press},
  date = {1996}
}
@book{PGM:betz,
  editor = {Preisendaz, Karl},
  title = {Papyri Graecae Magicae: Die griechischen Zauberpapyri},
  edition = {2},
  location = {Stuttgart},
  publisher = {Teubner},
  date = {1973/1974},
  shorthand = {\mkbibemph{PGM}},
  options = {skipbib,useeditor=false},
  xref = {betz:1996},
  related = {betz:1996},
  relatedtype = {labelname}
}
\end{filecontents}
\usepackage[style=verbose,minxrefs=1,backend=biber]{biblatex}
\addbibresource{\jobname.bib}
\renewbibmacro*{cite}{%
  \printfield{shorthand}%
  \setunit{\space}%
  \printfield{postnote}%
  \clearfield{postnote}%
  \setunit{\space}%
  \printtext[parens]{%
    \usebibmacro{related:init}%
    \usebibmacro{related}}%
}
\DeclareFieldFormat{postnote}{#1}
\newbibmacro*{related:labelname}[1]{%
  \entrydata{#1}{%
  \printnames[labelname]{author}}}
\begin{document}
\strut\vfill
\autocite[III. 1--164]{PGM:betz}
\printbiblist{shorthand}
\printbibliography
\end{document}
```

**Comment by dcpurton** [comment]
There is something else going on with the `skipbib` issue. I've just managed to produce an example that works while putting together a longer MWE for the tex.stackexchange question.

**Comment by dcpurton** [comment]
OK! You *also* need the `\printbiblist{shorthand}` line in the previous MWE example for it to fail. If you remove this line, then the bug is not exhibited. You need the combination of `skipbib`, `related`, and `printbiblist{shorthand}`.

I am in awe of you TeX skills if you can figure out what is happening...

**Comment by dcpurton** [comment]
Nope. I'm still wrong, because this example works fine! Perhaps it is to do with where `usebibmacro{related}` is called?

```TeX
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@mvcollection{ANF:Roberts+Donaldson,
  title = {The Ante-Nicene Fathers},
  editor = {Roberts, Alexander and Donaldson, James},
  origdate = {1885/1887},
  volumes = {10},
  location = {Peabody, MA},
  publisher = {Hendrickson},
  date = {1994},
  options = {useeditor=false},
  sortkey = {Ante-Nicene Fathers}
}
@mvcollection{ANF,
  title = {The Ante-Nicene Fathers},
  shorthand = {\mkbibemph{ANF}},
  options = {skipbib},
  xref = {ANF:Roberts+Donaldson}
}
@misc{clementinehomilies,
  title = {The Clementine Homilies, \mkbibemph{1.3}},
  xref = {ANF},
  related = {ANF},
  relatedtype = {ancienttext},
  options = {skipbib}
}
\end{filecontents}
\usepackage[style=verbose,minxrefs=1,backend=biber]{biblatex}
\addbibresource{\jobname.bib}
\newbibmacro*{related:ancienttext}[1]{%
  \entrydata*{#1}{%
    \printtext[parens]{%
      \printfield{shorthand}%
      \setunit{\postnotedelim}%
      \printfield{postnote}}}}
\renewbibmacro*{postnote}{%
  \iffieldundef{postnote}
    {}
    {\iffieldequalstr{relatedtype}{ancienttext}
       {}
       {\printfield{postnote}}}}
\renewcommand*{\newunitpunct}{\space}
\DefineBibliographyStrings{english}{%
  byeditor         = {edited by},
}
\begin{document}
\null\vfill
\autocite[8:223]{clementinehomilies}
\printbiblist{shorthand}
\printbibliography
\end{document}
```

**Comment by dcpurton** [comment]
I think I might be able to get things working in its current state! Here's a significantly more complex example incorporating an `altpostnote` [this is definitely a hack... please try not to break it ;)] and putting the related code where I'd actually put it in my style. And it works! So maybe the inclusion of `minxrefs` is going to be enough after all! If you are satisfied that there isn't a bug, then feel free to close this issue.

```TeX
\documentclass{article}
\usepackage{xparse}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@mvcollection{ANF:Roberts+Donaldson,
  title = {The Ante-Nicene Fathers},
  editor = {Roberts, Alexander and Donaldson, James},
  origdate = {1885/1887},
  volumes = {10},
  location = {Peabody, MA},
  publisher = {Hendrickson},
  date = {1994},
  options = {useeditor=false},
  sortkey = {Ante-Nicene Fathers}
}
@mvcollection{ANF,
  title = {The Ante-Nicene Fathers},
  shorthand = {\mkbibemph{ANF}},
  options = {skipbib},
  xref = {ANF:Roberts+Donaldson}
}
@misc{clementinehomilies,
  title = {The Clementine Homilies},
  xref = {ANF},
  related = {ANF},
  relatedtype = {ancienttext},
  options = {skipbib}
}
\end{filecontents}
\usepackage[style=verbose,minxrefs=1,backend=biber]{biblatex}
\addbibresource{\jobname.bib}

% ------------------------------------------------------------------
% ALTERNATE POSTNOTE MACROS
% ------------------------------------------------------------------

\ExplSyntaxOn
\cs_generate_variant:Nn \__xparse_split_argument:nnn { nno }
\cs_new_eq:NN \eSplitArgument  \__xparse_split_argument:nno
\DeclareDocumentCommand \splitpostnote
{ > { \eSplitArgument { 1 } { | } } m }
{ \savepostnotes #1 }
\DeclareDocumentCommand{\savepostnotes}{mm}{%
  \IfNoValueTF{#2}
    {\gdef\postnotelast{#1}}
    {\tl_if_empty:nF {#1}
       {\gdef\postnotefirst{#1}}%
     \tl_if_empty:nF {#2}
       {\gdef\postnotelast{#2}}}}
\ExplSyntaxOff

\makeatletter
\def\setuppostnotes{%
  \global\undef\postnotefirst
  \global\undef\postnotelast
  \splitpostnote{\abx@field@postnote}}
\makeatother

\renewbibmacro*{prenote}{%
  \iffieldundef{postnote}
    {}
    {\setuppostnotes
     \restorefield{postnote}{\postnotelast}%
     \restorefield{altpostnote}{\postnotefirst}}%
  \iffieldundef{prenote}
    {}
    {\printfield{prenote}%
     \setunit{\prenotedelim}}}

\DeclareFieldFormat{altpostnote}{\mkcomprange{#1}}

\DeclareBibliographyDriver{misc}{%
  \usebibmacro{citeindex}%
  \usebibmacro{begentry}%
  \usebibmacro{title}%
  \setunit{\postnotedelim}%
  \printfield{altpostnote}%
  \setunit{\addspace}%
  \printtext[parens]{%
    \usebibmacro{related:init}%
    \usebibmacro{related}%
    \setunit{\addspace}%
    \printfield{postnote}}%
  \usebibmacro{finentry}}

\renewbibmacro*{postnote}{%
  \iffieldundef{postnote}
    {}
    {\iffieldundef{related}
       {\printfield{postnote}}
       {}}}

\newbibmacro*{related:ancienttext}[1]{%
  \entrydata{#1}{%
    \printfield{shorthand}}}

\DefineBibliographyStrings{english}{%
  byeditor         = {edited by},
}

\begin{document}
\null\vfill
\autocite[1.3|8:223]{clementinehomilies}
\printbiblist{shorthand}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
I suspect this is all because, in verbose styles, citations use bib drivers and so `skipbib` has an effect. If this were changed when drivers were used in citations, this may be a cleaner solution for you?

**Comment by plk** [comment]
I think I know why this is happening now and is a variant of a problem reported by someone else a month ago. Can you try the latest 3.4 and biber 2.5? I don't think you should need to do any hacks - just use the related functions as you do in your second example above.

**Comment by dcpurton** [comment]
Ah - this is looking promising! My example above using `\entrydata{\thefield{xref}}{…}` works flawlessly! If this works, then only minimal changes will be needed to my style and even better only minimal changes the the database design. I can also more easily support all `biblatex` versions I think. I'll do some tests with my main style and report back here

**Comment by dcpurton** [comment]
Actually, looking at things, I think you're right. I'll use the `related` field. There are problems with entry options, and my code is getting messy…

Also, I think there is a bug: You can't have both an `xref` and a `crossref` field pointing to different entries. e.g., this MWE throws a warning from `biber` and doesn't work.

```TeX
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@mvcollection{NPNF1:schaff,
  title = {The Nicene and Post-Nicene Fathers, \mkbibemph{Series~1}},
  editor = {Schaff, Philip},
  origdate = {1886/1889},
  volumes = {14},
  location = {Peabody, MA},
  publisher = {Hendrickson},
  date = {1994},
  options = {useeditor=false},
  sortkey = {Nicene and Post-Nicene Fathers, Series 1}
}
@mvcollection{NPNF1,
  title = {The Nicene and Post-Nicene Fathers, \mkbibemph{Series~1}},
  shorthand = {\mkbibemph{NPNF\textsuperscript{1}}},
  options = {skipbib}
}
@book{augustine:letters,
  author = {Augustine},
  title = {The Letters of St.\@ Augustin},
  shorttitle = {Letters of St.\@ Augustin},
  volume = {1},
  crossref = {NPNF1:schaff},
  xref = {NPNF1}
}
\end{filecontents}
\usepackage[style=verbose,minxrefs=1,mincrossrefs=3,backend=biber]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\strut\vfill
\autocite{augustine:letters}
\autocite{augustine:letters}
\printbiblist{shorthand}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
This needed a bit more separation of xref/crossref internally in biber. Please pull the latest biber 2.5 now and try it.

**Comment by dcpurton** [comment]
Thanks! Entries with both an `xref` and `crossref` now work in my style.

Next question related to this thread:

I have some situations where I use the DeclareSourceMap feature to make a clone of a record. I then manipulate the clone a little. I need the clone to appear in the bibliography... Again I was using `\nocite{}` to achieve this. I'll try and come up with a small example for you. There may be a totally different way to achieve my outcome.

**Comment by plk** [comment]
Let's close this bug report and ask the question on TSE as the answer may be useful for others. If there is another bug, we'll open another ticket.

**Comment by dcpurton** [comment]
No worries. I found a way to do the last thing anyway. I can user source mapping to add an xref field to the cloned entry.

The following source map clones entries with both a shorthand and shortseries. The clone has the option skipbib appended (I only want it in the list of abbreviations) and the shorthand set to null. I think it's not possible to manipulate a cloned entry after it's been cloned, so I have made changes to the original entry, then cloned it, then restored the changes I made.

See below for a more full MWE of how I use this.

Thanks again for getting all this sorted out!

```
\DeclareSourcemap{
  \maps{
    \map[overwrite]{
      \step[fieldsource=shortseries, final]
      \step[fieldsource=shorthand, final]
      \step[fieldsource=shorthand, fieldtarget=usera]
      \step[fieldsource=options, fieldtarget=userb]
      \step[fieldset=options, fieldvalue={,skipbib}, append]
      \step[entryclone={shortseries-}]
      \step[fieldsource=usera, fieldtarget=shorthand]
      \step[fieldset=options, null]
      \step[fieldsource=userb, fieldtarget=options]
      \step[fieldsource=entrykey, match=\regexp{(.*)}]
      \step[fieldset=xref, fieldvalue={shortseries-$1}]
    }
  }
}
```

```TeX
\documentclass{article}
\usepackage{xparse}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{ABC,
  author = {Grayson, Albert Kirk},
  title = {Assyrian and Babylonian Chronicles},
  series = {Texts from Cuneiform Sources},
  shortseries = {TCS},
  number = {5},
  location = {Locust Valley, NY},
  publisher = {Augustin},
  date = {1975},
  shorthand = {\mkbibemph{ABC}}
}
@misc{esarhaddonchronicle,
  title = {Esarhaddon Chronicle},
  xref = {ABC},
  related = {ABC},
  options = {skipbib}
}
\end{filecontents}
\usepackage[style=verbose,minxrefs=1,mincrossrefs=3,backend=biber]{biblatex}
\ExplSyntaxOn
\cs_generate_variant:Nn \__xparse_split_argument:nnn { nno }
\cs_new_eq:NN \eSplitArgument  \__xparse_split_argument:nno
\DeclareDocumentCommand \splitpostnote
{ > { \eSplitArgument { 1 } { | } } m }
{ \savepostnotes #1 }
\DeclareDocumentCommand{\savepostnotes}{mm}{%
  \IfNoValueTF{#2}
    {\gdef\postnotelast{#1}}
    {\tl_if_empty:nF {#1}
       {\gdef\postnotefirst{#1}}%
     \tl_if_empty:nF {#2}
       {\gdef\postnotelast{#2}}}}
\ExplSyntaxOff

\makeatletter
\def\setuppostnotes{%
  \global\undef\postnotefirst
  \global\undef\postnotelast
  \splitpostnote{\abx@field@postnote}}
\makeatother

\renewbibmacro*{prenote}{%
  \iffieldundef{postnote}
    {}
    {\setuppostnotes
     \restorefield{postnote}{\postnotelast}%
     \restorefield{altpostnote}{\postnotefirst}}%
  \iffieldundef{prenote}
    {}
    {\printfield{prenote}%
     \setunit{\prenotedelim}}}

\DeclareFieldFormat{altpostnote}{\mkcomprange{#1}}
\DeclareFieldFormat{postnote}{\mkcomprange{#1}}

\renewbibmacro*{postnote}{%
  \iffieldundef{postnote}
    {}
    {\iffieldundef{related}
       {\printfield{postnote}}
       {}}}

\renewbibmacro*{cite}{%
  \usebibmacro{cite:citepages}%
  \iffieldundef{shorthand}
    {\usebibmacro{cite:full}}
    {\usebibmacro{cite:shorthand}}}

\DeclareBibliographyDriver{misc}{%
  \usebibmacro{begentry}%
  \usebibmacro{title}%
  \setunit{\postnotedelim}%
  \printfield{altpostnote}%
  \setunit{\addspace}%
  \printtext[parens]{%
    \usebibmacro{related:init}%
    \usebibmacro{related}%
    \setunit{\postnotedelim}%
    \printfield{postnote}}%
  \usebibmacro{finentry}}

\DeclareBibliographyDriver{book}{%
  \usebibmacro{begentry}%
  \usebibmacro{author/editor+others/translator+others}%
  \newunit
  \printfield{title}%
  \newunit
  \usebibmacro{byauthor}
  \newunit
  \printfield{shortseries}%
  \setunit{\addspace}%
  \printfield{number}%
  \newunit
  \usebibmacro{publisher+location+date}%
  \usebibmacro{finentry}}

\DeclareFieldFormat[misc]{title}{#1}

\renewbibmacro*{related:default}[1]{%
  \ifciteseen
    {\entrydata*{#1}{\printfield{shorthand}}}
    {\entrydata*{#1}{\usedriver{}{\thefield{entrytype}}}}}

\newlength{\abbrevwidth}

\def\setmaxlength#1#2{%
  \ifdim\dimexpr#2>\dimexpr#1
    \global\setlength{#1}{#2}%
  \fi
}

\defbibenvironment{shorthand}
  {\list
     {\printfield[shorthandwidth]{shorthand}%
      \ifboolexpr{
        not test {\iffieldundef{shorthand}}
        and
        not test {\iffieldundef{shortseries}}
      }
        {}
        {\printfield[shorthandwidth]{shortseries}}}
     {\setmaxlength{\abbrevwidth}{\shorthandwidth}%
      \setmaxlength{\abbrevwidth}{\shortserieswidth}%
      \setlength{\labelwidth}{\abbrevwidth}%
      \setlength{\leftmargin}{\labelwidth}%
      \setlength{\labelsep}{\biblabelsep}%
      \addtolength{\leftmargin}{\labelsep}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}%
      \renewcommand*{\makelabel}[1]{##1\hss}}}
  {\endlist}
  {\item}

\DeclareBiblistFilter{shorthand}{
  \filteror{
    \filter[type=field,filter=shorthand]
    \filter[type=field,filter=shortseries]
  }
}

\DeclareSortingScheme{shorthand}{%
  \sort{%
    \field{shorthand}%
    \field{shortseries}%
  }%
}

\DeclareBibliographyDriver{shorthand}{%
  \iffieldundef{shorthand}
    {\printfield{series}}
    {\usedriver
       {}
       {\thefield{entrytype}}}
  \finentry}

\DeclareSourcemap{
  \maps{
    \map[overwrite]{
      \step[fieldsource=shortseries, final]
      \step[fieldsource=shorthand, final]
      \step[fieldsource=shorthand, fieldtarget=usera]
      \step[fieldsource=options, fieldtarget=userb]
      \step[fieldset=options, fieldvalue={,skipbib}, append]
      \step[entryclone={shortseries-}]
      \step[fieldsource=usera, fieldtarget=shorthand]
      \step[fieldset=options, null]
      \step[fieldsource=userb, fieldtarget=options]
      \step[fieldsource=entrykey, match=\regexp{(.*)}]
      \step[fieldset=xref, fieldvalue={shortseries-$1}]
    }
  }
}

\addbibresource{\jobname.bib}
\begin{document}
\strut\vfill
\autocite[lines 3--4|125]{esarhaddonchronicle}
\autocite[lines 3--4|125]{esarhaddonchronicle}
\printbiblist{shorthand}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
You can fetch biber 2.5 again from SF - it now allows you to modify clones. You just clone and then use the clone's key as the argument to `entrytarget`.

**Comment by dcpurton** [comment]
Hmmm... Two problems.
  - I can't make this work. When I try an change something on the clone, both the clone and original are changed.
  - It **breaks** the method I was using in the most recent MWE in this thread! (Broken from commit https://github.com/plk/biber/commit/e56a407948d935a450568eec4b02a0de3fdb5035)

However, this gives me an idea for using entrynew. It doesn't work at the moment, but, I'll start a new issue with a feature request.

**Comment by dcpurton** [comment]
I think the the two points in the previous comment are connected. Any changes to either entry after the clone affect both clone and original.

**Comment by plk** [comment]
This is a basically a bug that needs to be addressed in the Text::BibTeX module. I have submitted a patch to add the new functionality and just waiting for it to be pushed to CPAN.

**Comment by plk** [comment]
Should be fixed now in latest biber 2.5

**Comment by dcpurton** [comment]
Thank you for sorting out everything! I have a good working solution now.
