### ISSUE TITLE
Consider 'sortyear' before warning

### ISSUE THREAD

**Issue by samcarter8** [plk/biblatex#480]
Perhaps it would make sense to check if a `sortyear` is given before issuing the warning 

> WARN - year field 'in preparation' in entry 'test' is not an integer - this will probably not sort properly.

I know the following example is a great abuse of the fields and a total hack:

```
@unpublished{test,
	author = {I. Test},
	title = "{Bla}",
	pubstate = {inpreparation},
	year = {in preparation},
	sortyear = 2017,
	}
```

and there are better ways to achieve the output. Nevertheless I believe that with giving a `sortyear` as integer should prevent the above warning.

**Comment by plk** [comment]
Yes, this is reasonable - this is fixed in 2.7 dev version.

**Comment by samcarter8** [comment]
Thanks!

**Comment by samcarter8** [comment]
I updated my TeXLive and it know says `INFO - This is Biber 2.7` but I still get this warning. Do I need some other version then the one included in TeXLive?

**Comment by plk** [comment]
Hmm, the fix wasn't reliable and had a race condition. Now it is fixed in the 2.8 dev branch. DEV binaries will be updated tonight.

**Comment by samcarter8** [comment]
Thank you so much! It works perfectly!

**Comment by keithbriggs** [comment]
I'm still getting this warning in 2025 with biber 2.17!
```

@article{Nomina-15-Fellows-Jensen-Place-names,
  author=  {Gillian Fellows-Jensen},
  title=   {Place-names in \textbf{-{\th}orp}: in retrospect and in turmoil},
  journal= {Nomina},
  volume=  {15},
  pages=   {35--51},
  year=    {1991--1992},
  sortyear={1992},
}
```


`WARN - legacy year field '1991--1992' in entry 'Nomina-15-Fellows-Jensen-Place-names' is not an integer - this will probably not sort properly.
`

**Comment by hvoss49** [comment]
See https://tex.stackexchange.com/questions/449259/year-range-in-bibliography-with-biber
