### ISSUE TITLE
overwrite=true does not work for fieldtarget

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#535]
This came up in http://tex.stackexchange.com/q/353722/35864

It seems as though `overwrite=true` has no effect when used in a `fieldsource`/`fieldtarget` combination.

In the MWE below I would expect both notes to show 'foo', yet in `worman` the original value 'bar' is not overwritten.
```
\documentclass{article}
\usepackage{filecontents}
\usepackage[
  backend=biber,
  style=authoryear-comp,
]{biblatex}

\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map[overwrite=true]{
       \step[fieldsource=keywords, fieldtarget=note]
    }
  }
}

\begin{filecontents}{\jobname.bib}
@book{worman,
  author    = {Worman, Nancy},
  title     = {The Cast of Character},
  date      = 2002,
  keyword   = {foo},
  note      = {bar},
}
@book{wilde,
  author   = {Wilde, Oscar},
  title    = {The Importance of Being Earnest},
  year     = 1899,
  keywords = {foo},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
````

**Comment by plk** [comment]
This was a bug, now fixed in 2.8 DEV version.

**Comment by moewew** [comment]
Thank you for the swift reply. It works like a charm with the 2.8 DEV version from sourceforge.

**Comment by LSinev** [comment]
Seems like in biblatex 3.7 this MWE produces:

> Wilde, Oscar (1899). The Importance of Being Earnest. foo.
Worman, Nancy (2002). The Cast of Character. bar.

So it is not fixed for 3.7.

**Comment by plk** [comment]
Yes, you need the DEV 2.8 version of biber which needs the DEV 3.8 version of biblatex.
